from fastapi import (
    APIRouter, 
    Depends, 
    HTTPException, 
    status
)

from sqlalchemy.ext.asyncio import AsyncSession

from typing import List, Dict, Optional, Any
import pandas as pd
import logging

from database.session import get_db
from database.model import User, Transaction, FraudRingSummary

from auth.deps import get_current_user

from service.embeddings.create_vector_db import CPUEmbeddings
from service.embeddings.fiass_calculate import FAISSVectorStore
from service.ingestion import DataIngestionService

from schema.chatbout import (
    ChatQueryResponse,
    ChatQueryRequest,
    SessionSummaryResponse,
    DatasetInfoResponse,
    BuildVectorDBRequest,
    BuildVectorDBResponse
)

from chatbot import FraudDetectionChatbot, VECTOR_AVAILABLE

logger = logging.getLogger(__name__)

_embeddings_instance: Optional[CPUEmbeddings] = None
_vector_store_instance: Optional[FAISSVectorStore] = None
_chatbot_cache: Dict[str, FraudDetectionChatbot] = {}


def get_embeddings() -> CPUEmbeddings:
    """Get or create singleton embeddings instance."""
    global _embeddings_instance
    if _embeddings_instance is None:
        logger.info("Initializing CPUEmbeddings for chatbot")
        _embeddings_instance = CPUEmbeddings(training_mode=False)
    return _embeddings_instance


def get_vector_store() -> FAISSVectorStore:
    """Get or create singleton vector store instance."""
    global _vector_store_instance
    if _vector_store_instance is None:
        logger.info("Initializing FAISSVectorStore for chatbot")
        _vector_store_instance = FAISSVectorStore()
    return _vector_store_instance


router = APIRouter(prefix="/chatbot", tags=["Chatbot"])


async def load_user_transactions(tenant_id: str, db: AsyncSession) -> pd.DataFrame:
    """
    Load user's transaction data from database.
    ENHANCED: Now also includes fraud detection results from engine.
    
    Args:
        tenant_id: User ID
        db: Database session
        
    Returns:
        DataFrame with transactions
    """
    from sqlalchemy import select
    
    query = select(Transaction).where(Transaction.tenant_user_id == tenant_id)
    result = await db.execute(query)
    transactions = result.scalars().all()
    
    if not transactions:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="No transaction data found. Please upload data first via /upload/full-pipeline"
        )
    
    # Convert to DataFrame
    df = pd.DataFrame([{
        "transaction_id": t.transaction_id,
        "sender": t.sender,
        "receiver": t.receiver,
        "amount": float(t.amount) if t.amount else 0.0,
        "timestamp": t.timestamp,
        "sender_country": t.sender_country,
        "receiver_country": t.receiver_country,
        "sender_kyc": t.sender_kyc,
        "txn_method": t.txn_method,
        "device_id": t.device_id,
        "sender_acct_age": int(t.sender_acct_age) if t.sender_acct_age else 0,
        "velocity_mins": float(t.velocity_mins) if t.velocity_mins else 0.0,
        "is_round_amount": int(t.is_round_amount) if t.is_round_amount else 0
    } for t in transactions])
    
    logger.info(f"Loaded {len(df)} transactions for tenant {tenant_id}")
    return df


async def load_fraud_summaries(tenant_id: str, db: AsyncSession) -> Optional[pd.DataFrame]:
    """
    Load fraud ring summaries generated by the detection engine.
    This gives the chatbot access to fraud patterns detected by your 10 algorithms.
    
    Args:
        tenant_id: User ID
        db: Database session
        
    Returns:
        DataFrame with fraud summaries or None if none exist
    """
    from sqlalchemy import select
    
    query = select(FraudRingSummary).where(FraudRingSummary.tenant_user_id == tenant_id)
    result = await db.execute(query)
    summaries = result.scalars().all()
    
    if not summaries:
        logger.info(f"No fraud summaries found for tenant {tenant_id}")
        return None
    
    # Convert to DataFrame
    df = pd.DataFrame([{
        "ring_id": s.ring_id,
        "pattern_type": s.pattern_type,
        "member_count": int(s.member_count) if s.member_count else 0,
        "risk_score": float(s.risk_score) if s.risk_score else 0.0,
        "risk_category": s.risk_category,
        "member_accounts": s.member_accounts,  # JSON field with account list
        "created_at": s.created_at
    } for s in summaries])
    
    logger.info(f"Loaded {len(df)} fraud summaries for tenant {tenant_id}")
    return df


async def build_fraud_context(tenant_id: str, db: AsyncSession) -> str:
    """
    Build a text context from fraud summaries to help chatbot understand detected patterns.
    
    Args:
        tenant_id: User ID
        db: Database session
        
    Returns:
        Text summary of detected fraud patterns
    """
    fraud_df = await load_fraud_summaries(tenant_id, db)
    
    if fraud_df is None or len(fraud_df) == 0:
        return "No fraud patterns detected yet."
    
    # Build summary text
    context_parts = [
        f"Detected Fraud Patterns Summary ({len(fraud_df)} patterns):\n"
    ]
    
    # Group by pattern type
    pattern_counts = fraud_df.groupby('pattern_type').agg({
        'ring_id': 'count',
        'member_count': 'sum',
        'risk_score': 'max'
    }).to_dict('index')
    
    for pattern, stats in pattern_counts.items():
        context_parts.append(
            f"- {pattern}: {stats['ring_id']} rings, "
            f"{stats['member_count']} accounts involved, "
            f"max risk: {stats['risk_score']:.2f}"
        )
    
    # Add high-risk patterns
    high_risk = fraud_df[fraud_df['risk_category'] == 'High'].sort_values('risk_score', ascending=False)
    if len(high_risk) > 0:
        context_parts.append(f"\nHigh-Risk Patterns: {len(high_risk)}")
        for _, row in high_risk.head(5).iterrows():
            context_parts.append(
                f"  • {row['pattern_type']} ring {row['ring_id']}: "
                f"{row['member_count']} accounts, risk {row['risk_score']:.2f}"
            )
    
    return "\n".join(context_parts)


async def index_fraud_summaries(
    tenant_id: str,
    db: AsyncSession,
    vector_store: FAISSVectorStore,
    embeddings: CPUEmbeddings
) -> Dict:
    """
    Index fraud summaries into FAISS for semantic search.
    This allows the chatbot to search for fraud patterns using natural language.
    
    Args:
        tenant_id: User ID
        db: Database session
        vector_store: FAISS vector store
        embeddings: Embeddings instance
        
    Returns:
        Indexing statistics
    """
    fraud_df = await load_fraud_summaries(tenant_id, db)
    
    if fraud_df is None or len(fraud_df) == 0:
        return {"status": "skipped", "reason": "no_fraud_data"}
    
    # Convert each fraud pattern to text
    documents = []
    metadata_list = []
    
    for _, row in fraud_df.iterrows():
        # Create rich text description of the fraud pattern
        doc_text = (
            f"Fraud Pattern: {row['pattern_type']} | "
            f"Ring ID: {row['ring_id']} | "
            f"Accounts Involved: {row['member_count']} | "
            f"Risk Score: {row['risk_score']} | "
            f"Risk Category: {row['risk_category']} | "
            f"Members: {row['member_accounts']}"
        )
        documents.append(doc_text)
        
        # Metadata for filtering
        metadata_list.append({
            "ring_id": str(row['ring_id']),
            "pattern_type": str(row['pattern_type']),
            "risk_score": str(row['risk_score']),
            "risk_category": str(row['risk_category']),
            "document_type": "fraud_summary"  # Important for filtering
        })
    
    # Embed documents
    all_embeddings = embeddings.embed_documents(documents)
    
    # Add to vector store with special document type
    stats = vector_store.add_documents(
        tenant_id=tenant_id,
        embeddings=all_embeddings,
        documents=documents,
        metadata=metadata_list,
        document_type="fraud_summary"  # This allows filtering in searches
    )
    
    logger.info(f"Indexed {len(documents)} fraud summaries for tenant {tenant_id}")
    return stats


async def get_or_create_chatbot(
    tenant_id: str,
    db: AsyncSession
) -> FraudDetectionChatbot:
    """
    Get cached chatbot or create new one.
    ENHANCED: Now includes fraud summary context.
    
    Args:
        tenant_id: User ID
        db: Database session
        
    Returns:
        Chatbot instance with fraud context
    """
    # Check cache
    if tenant_id in _chatbot_cache:
        logger.debug(f"Using cached chatbot for tenant {tenant_id}")
        return _chatbot_cache[tenant_id]
    
    # Load transaction data
    df = await load_user_transactions(tenant_id, db)
    fraud_df = await load_fraud_summaries(tenant_id, db)
    
    # Initialize chatbot
    logger.info(f"Creating new chatbot for tenant {tenant_id}")
    
    # Get embeddings and vector store
    embeddings = get_embeddings()
    vector_store = get_vector_store()
    
    # Create chatbot
    chatbot = FraudDetectionChatbot(
        df=df,
        fraud_summary_df=fraud_df,
        vector_store=vector_store if VECTOR_AVAILABLE else None,
        embeddings=embeddings if VECTOR_AVAILABLE else None,
        default_tenant_id=tenant_id
    )
    
    # Index fraud summaries if available
    if VECTOR_AVAILABLE:
        try:
            fraud_stats = await index_fraud_summaries(tenant_id, db, vector_store, embeddings)
            logger.info(f"Fraud summary indexing: {fraud_stats}")
        except Exception as e:
            logger.warning(f"Could not index fraud summaries: {e}")
    
    # Cache it
    _chatbot_cache[tenant_id] = chatbot
    
    logger.info(f"Chatbot created and cached for tenant {tenant_id}")
    return chatbot


@router.get(
    "/fraud-patterns",
    status_code=status.HTTP_200_OK,
    summary="Get fraud pattern summary"
)
async def get_fraud_patterns(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """
    Get a summary of detected fraud patterns from the detection engine.
    This shows what patterns the NLP chatbot knows about.
    """
    try:
        fraud_df = await load_fraud_summaries(current_user.user_id, db)
        
        if fraud_df is None or len(fraud_df) == 0:
            return {
                "status": "success",
                "message": "No fraud patterns detected yet. Run fraud detection first.",
                "patterns": []
            }
        
        # Convert to summary
        patterns_summary = []
        for pattern_type in fraud_df['pattern_type'].unique():
            pattern_data = fraud_df[fraud_df['pattern_type'] == pattern_type]
            patterns_summary.append({
                "pattern_type": pattern_type,
                "ring_count": len(pattern_data),
                "total_accounts": int(pattern_data['member_count'].sum()),
                "avg_risk_score": float(pattern_data['risk_score'].mean()),
                "max_risk_score": float(pattern_data['risk_score'].max()),
                "high_risk_count": len(pattern_data[pattern_data['risk_category'] == 'High'])
            })
        
        return {
            "status": "success",
            "total_patterns": len(fraud_df),
            "pattern_types": len(patterns_summary),
            "patterns": patterns_summary
        }
        
    except Exception as e:
        logger.error(f"Error getting fraud patterns: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error getting fraud patterns: {str(e)}"
        )


def convert_table_data(table_data: Any) -> Optional[List[Dict]]:
    """Convert DataFrame or other table data to list of dicts."""
    if table_data is None:
        return None
    
    if isinstance(table_data, pd.DataFrame):
        # Limit to 100 rows for response size
        return table_data.head(100).to_dict('records')
    
    if isinstance(table_data, list):
        return table_data[:100]
    
    return None


@router.post(
    "/query",
    response_model=ChatQueryResponse,
    status_code=status.HTTP_200_OK,
    summary="Query chatbot with natural language",
    description="""
    Ask questions about your transaction data in natural language.
    
    Example queries:
    - "How many transactions are there?"
    - "What is the average transaction amount?"
    - "Show me high-risk transactions"
    - "Group transactions by country"
    - "Find suspicious patterns"
    """
)
async def chat_query(
    request: ChatQueryRequest,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Answer a natural language query about fraud detection data."""
    try:
        # Get chatbot
        chatbot = await get_or_create_chatbot(current_user.user_id, db)
        
        # Process query
        response = chatbot.answer_query(
            user_query=request.query,
            session_id=request.session_id,
            include_followup=request.include_followup,
            include_trace=request.include_trace
        )
        
        # Convert table data
        response["table_data"] = convert_table_data(response.get("table_data"))
        
        return ChatQueryResponse(**response)
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error processing query: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error processing query: {str(e)}"
        )


@router.get(
    "/session/{session_id}",
    response_model=SessionSummaryResponse,
    status_code=status.HTTP_200_OK,
    summary="Get session summary"
)
async def get_session_summary(
    session_id: str,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Get conversation history and summary for a session."""
    try:
        chatbot = await get_or_create_chatbot(current_user.user_id, db)
        summary = chatbot.get_session_summary(session_id)
        
        return SessionSummaryResponse(
            session_id=session_id,
            interaction_count=summary.get("interaction_count", 0),
            interactions=summary.get("interactions", [])
        )
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error getting session summary: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error getting session summary: {str(e)}"
        )


@router.post(
    "/session/{session_id}/reset",
    status_code=status.HTTP_200_OK,
    summary="Reset session"
)
async def reset_session(
    session_id: str,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Reset conversation history for a session."""
    try:
        chatbot = await get_or_create_chatbot(current_user.user_id, db)
        chatbot.reset_session(session_id)
        
        return {
            "status": "success",
            "message": f"Session {session_id} reset successfully"
        }
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error resetting session: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error resetting session: {str(e)}"
        )


@router.get(
    "/dataset/info",
    response_model=DatasetInfoResponse,
    status_code=status.HTTP_200_OK,
    summary="Get dataset information"
)
async def get_dataset_info(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Get information about the loaded transaction dataset."""
    try:
        chatbot = await get_or_create_chatbot(current_user.user_id, db)
        info = chatbot.get_dataset_info()
        
        formatted_info = {
            "rows": info.get("transaction_count", 0),
            "columns": info.get("column_names", []),
            "kyc_distribution": info.get("kyc_dist", {}),
            "method_distribution": info.get("method_dist", {}),
            "country_distribution": info.get("country_dist", {}),
            "amount_stats": {
                "min": info.get("min_amount"),
                "max": info.get("max_amount"),
                "avg": info.get("avg_amount"),
                "total": info.get("total_amount")
            }
        }

        return DatasetInfoResponse(**formatted_info)
        # return DatasetInfoResponse(**info)
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error getting dataset info: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error getting dataset info: {str(e)}"
        )


@router.post(
    "/vector-db/build",
    response_model=BuildVectorDBResponse,
    status_code=status.HTTP_200_OK,
    summary="Build vector database"
)
async def build_vector_db(
    request: BuildVectorDBRequest,
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """Build or rebuild the vector database for semantic search."""
    if not VECTOR_AVAILABLE:
        raise HTTPException(
            status_code=status.HTTP_400_BAD_REQUEST,
            detail="Vector search is not available. Check VectorRetriever installation."
        )
    
    try:
        chatbot = await get_or_create_chatbot(current_user.user_id, db)
        
        result = chatbot.build_vector_db(
            tenant_id=current_user.user_id,
            force_rebuild=request.force_rebuild
        )
        
        return BuildVectorDBResponse(**result)
        
    except HTTPException:
        raise
    except Exception as e:
        logger.error(f"Error building vector DB: {e}", exc_info=True)
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Error building vector DB: {str(e)}"
        )
    


@router.get(
    "/vector-index/stats",
    status_code=status.HTTP_200_OK,
    summary="Get vector index statistics",
    tags=["Vector Search"]
)
async def get_vector_index_stats(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """
    Get statistics about your FAISS vector index.
    Shows total documents, uploads, and breakdown by type.
    """
    try:
        service = DataIngestionService(db)
        
        stats = await service.get_tenant_index_stats(current_user.user_id)
        
        if stats is None:
            return {
                "status": "success",
                "tenant_id": current_user.user_id,
                "message": "No vector index found. Upload data with embeddings enabled to create one.",
                "has_index": False
            }
        
        return {
            "status": "success",
            **stats,
            "has_index": True
        }
    
    except AttributeError:
        raise HTTPException(
            status_code=status.HTTP_501_NOT_IMPLEMENTED,
            detail="Vector indexing not available. Enable embeddings during upload."
        )
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to get index stats: {str(e)}"
        )




@router.delete(
    "/vector-index",
    status_code=status.HTTP_200_OK,
    summary="Delete vector index",
    tags=["Vector Search"]
)
async def delete_vector_index(
    current_user: User = Depends(get_current_user),
    db: AsyncSession = Depends(get_db)
):
    """
    Delete your entire FAISS vector index.
    This will remove all embeddings but not the database records.
    """
    try:
        service = DataIngestionService(db)
        
        success = await service.delete_tenant_index(current_user.user_id)
        
        if success:
            # Also clear chatbot cache since index is deleted
            global _chatbot_cache
            if current_user.user_id in _chatbot_cache:
                del _chatbot_cache[current_user.user_id]
            
            return {
                "status": "success",
                "tenant_id": current_user.user_id,
                "message": "Vector index deleted successfully"
            }
        else:
            raise HTTPException(
                status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
                detail="Failed to delete vector index"
            )
    
    except AttributeError:
        raise HTTPException(
            status_code=status.HTTP_501_NOT_IMPLEMENTED,
            detail="Vector indexing not available."
        )
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(
            status_code=status.HTTP_500_INTERNAL_SERVER_ERROR,
            detail=f"Failed to delete index: {str(e)}"
        )


@router.delete(
    "/cache",
    status_code=status.HTTP_200_OK,
    summary="Clear chatbot cache"
)
async def clear_chatbot_cache(
    current_user: User = Depends(get_current_user)
):
    """Clear cached chatbot instance for current user."""
    global _chatbot_cache
    
    if current_user.user_id in _chatbot_cache:
        del _chatbot_cache[current_user.user_id]
        logger.info(f"Cleared chatbot cache for tenant {current_user.user_id}")
        
        return {
            "status": "success",
            "message": "Chatbot cache cleared. Next query will reload data."
        }
    
    return {
        "status": "success",
        "message": "No cached chatbot found for user."
    }


@router.get(
    "/health",
    status_code=status.HTTP_200_OK,
    summary="Health check"
)
async def chatbot_health():
    """Check chatbot service health and status."""
    try:
        embeddings = get_embeddings()
        vector_store = get_vector_store()
        
        return {
            "status": "healthy",
            "vector_available": VECTOR_AVAILABLE,
            "embeddings_cache_size": embeddings.get_cache_size(),
            "cached_chatbots": len(_chatbot_cache),
            "embeddings_model": embeddings.model_name
        }
    except Exception as e:
        logger.error(f"Health check failed: {e}", exc_info=True)
        return {
            "status": "unhealthy",
            "error": str(e)
        }

