from fastapi import (
    HTTPException, 
    status
)

from sqlalchemy.ext.asyncio import AsyncSession

from typing import Dict, Optional, List, Any
import pandas as pd
import logging

from database.model import Transaction, FraudRingSummary

from service.embeddings.create_vector_db import CPUEmbeddings
from service.embeddings.fiass_calculate import FAISSVectorStore
from service.ingestion import DataIngestionService


from chatbot import FraudDetectionChatbot, VECTOR_AVAILABLE


logger = logging.getLogger(__name__)

_embeddings_instance: Optional[CPUEmbeddings] = None
_chatbot_cache: Dict[str, FraudDetectionChatbot] = {}


def get_embeddings() -> CPUEmbeddings:
    """Get or create singleton embeddings instance."""
    global _embeddings_instance
    if _embeddings_instance is None:
        logger.info("Initializing CPUEmbeddings for chatbot")
        _embeddings_instance = CPUEmbeddings(training_mode=False)
    return _embeddings_instance


def get_vector_store(db: AsyncSession) -> FAISSVectorStore:
    """
    Get vector store instance with database session.
    NOTE: Not cached because it needs db session.
    """
    logger.debug("Creating FAISSVectorStore instance with db session")
    return FAISSVectorStore(db)


async def load_user_transactions(tenant_id: str, db: AsyncSession) -> pd.DataFrame:
    """
    Load user's transaction data from database.
    ENHANCED: Now also includes fraud detection results from engine.
    
    Args:
        tenant_id: User ID
        db: Database session
        
    Returns:
        DataFrame with transactions
    """
    from sqlalchemy import select
    
    query = select(Transaction).where(Transaction.tenant_user_id == tenant_id)
    result = await db.execute(query)
    transactions = result.scalars().all()
    
    if not transactions:
        raise HTTPException(
            status_code=status.HTTP_404_NOT_FOUND,
            detail="No transaction data found. Please upload data first via /upload/full-pipeline"
        )
    
    # Convert to DataFrame
    df = pd.DataFrame([{
        "transaction_id": t.transaction_id,
        "sender": t.sender,
        "receiver": t.receiver,
        "amount": float(t.amount) if t.amount else 0.0,
        "timestamp": t.timestamp,
        "sender_country": t.sender_country,
        "receiver_country": t.receiver_country,
        "sender_kyc": t.sender_kyc,
        "txn_method": t.txn_method,
        "device_id": t.device_id,
        "sender_acct_age": int(t.sender_acct_age) if t.sender_acct_age is not None else 0,
        "velocity_mins": float(t.velocity_mins) if t.velocity_mins is not None else 0.0,
        "is_round_amount": bool(t.is_round_amount) if t.is_round_amount is not None else False
    } for t in transactions])
    
    logger.info(f"Loaded {len(df)} transactions for tenant {tenant_id}")
    return df


async def load_fraud_summaries(tenant_id: str, db: AsyncSession) -> Optional[pd.DataFrame]:
    """
    Load fraud ring summaries generated by the detection engine.
    This gives the chatbot access to fraud patterns detected by your 10 algorithms.
    
    Args:
        tenant_id: User ID
        db: Database session
        
    Returns:
        DataFrame with fraud summaries or None if none exist
    """
    from sqlalchemy import select
    
    query = select(FraudRingSummary).where(FraudRingSummary.tenant_user_id == tenant_id)
    result = await db.execute(query)
    summaries = result.scalars().all()
    
    if not summaries:
        logger.info(f"No fraud summaries found for tenant {tenant_id}")
        return None
    
    # Convert to DataFrame
    df = pd.DataFrame([{
        "ring_id": s.ring_id,
        "pattern_type": s.pattern_type,
        "member_count": int(s.member_count) if s.member_count else 0,
        "risk_score": float(s.risk_score) if s.risk_score else 0.0,
        "risk_category": s.risk_category,
        "member_accounts": s.member_accounts,  # JSON field with account list
        "created_at": s.created_at
    } for s in summaries])
    
    logger.info(f"Loaded {len(df)} fraud summaries for tenant {tenant_id}")
    return df


async def index_fraud_summaries(
    tenant_id: str,
    db: AsyncSession,
    vector_store: FAISSVectorStore,
    embeddings: CPUEmbeddings
) -> Dict:
    """
    Index fraud summaries into FAISS for semantic search.
    This allows the chatbot to search for fraud patterns using natural language.
    
    Args:
        tenant_id: User ID
        db: Database session
        vector_store: FAISS vector store
        embeddings: Embeddings instance
        
    Returns:
        Indexing statistics
    """
    fraud_df = await load_fraud_summaries(tenant_id, db)
    
    if fraud_df is None or len(fraud_df) == 0:
        return {"status": "skipped", "reason": "no_fraud_data"}
    
    # Convert each fraud pattern to text
    documents = []
    metadata_list = []
    
    for _, row in fraud_df.iterrows():
        # Create rich text description of the fraud pattern
        doc_text = (
            f"Fraud Pattern: {row['pattern_type']} | "
            f"Ring ID: {row['ring_id']} | "
            f"Accounts Involved: {row['member_count']} | "
            f"Risk Score: {row['risk_score']} | "
            f"Risk Category: {row['risk_category']} | "
            f"Members: {row['member_accounts']}"
        )
        documents.append(doc_text)
        
        # Metadata for filtering
        metadata_list.append({
            "ring_id": str(row['ring_id']),
            "pattern_type": str(row['pattern_type']),
            "risk_score": str(row['risk_score']),
            "risk_category": str(row['risk_category']),
            "document_type": "fraud_summary"  # Important for filtering
        })
    
    # Embed documents
    all_embeddings = embeddings.embed_documents(documents)
    
    # Add to vector store with special document type
    stats = await vector_store.add_documents(
        tenant_id=tenant_id,
        embeddings=all_embeddings,
        documents=documents,
        metadata=metadata_list,
        document_type="fraud_summary"  # This allows filtering in searches
    )
    
    logger.info(f"Indexed {len(documents)} fraud summaries for tenant {tenant_id}")
    return stats


async def get_or_create_chatbot(
    tenant_id: str,
    db: AsyncSession
) -> FraudDetectionChatbot:
    """
    Get cached chatbot or create new one.
    ENHANCED: Now includes fraud summary context.
    UPDATED: Uses db-aware FAISSVectorStore.
    
    Args:
        tenant_id: User ID
        db: Database session
        
    Returns:
        Chatbot instance with fraud context
    """
    # Check cache
    if tenant_id in _chatbot_cache:
        logger.debug(f"Using cached chatbot for tenant {tenant_id}")
        return _chatbot_cache[tenant_id]
    
    # Load transaction data
    df = await load_user_transactions(tenant_id, db)
    fraud_df = await load_fraud_summaries(tenant_id, db)
    
    # Initialize chatbot
    logger.info(f"Creating new chatbot for tenant {tenant_id}")
    
    # Get embeddings and vector store (with db session)
    embeddings = get_embeddings()
    vector_store = get_vector_store(db)  
    
    # Create chatbot
    chatbot = FraudDetectionChatbot(
        df=df,
        fraud_summary_df=fraud_df,
        vector_store=vector_store if VECTOR_AVAILABLE else None,
        embeddings=embeddings if VECTOR_AVAILABLE else None,
        default_tenant_id=tenant_id
    )
    
    # Index fraud summaries if available
    if VECTOR_AVAILABLE and fraud_df is not None:
        try:
            fraud_stats = await index_fraud_summaries(tenant_id, db, vector_store, embeddings)
            logger.info(f"Fraud summary indexing: {fraud_stats}")
        except Exception as e:
            logger.warning(f"Could not index fraud summaries: {e}")
    
    # Cache it
    _chatbot_cache[tenant_id] = chatbot
    
    logger.info(f"Chatbot created and cached for tenant {tenant_id}")
    return chatbot


def convert_table_data(table_data: Any) -> Optional[List[Dict]]:
    """Convert DataFrame or other table data to list of dicts."""
    if table_data is None:
        return None
    
    if isinstance(table_data, pd.DataFrame):
        # Limit to 100 rows for response size
        return table_data.head(100).to_dict('records')
    
    if isinstance(table_data, list):
        return table_data[:100]
    
    return None
