import uuid
from datetime import datetime

from sqlalchemy import (
    Column,
    String, 
    Integer, 
    Text, 
    Float, 
    Boolean, 
    ForeignKey, 
    DateTime, 
    Numeric,
    LargeBinary
)

from sqlalchemy.orm import relationship
from sqlalchemy.dialects.postgresql import JSONB

from .base import Base
from core.security import hash_password, verify_password


class User(Base):
    """
    Tenant User Table (e.g., Bank Managers / Organizations)
    """
    __tablename__ = "users"

    user_id = Column(String(36), primary_key=True, default=lambda: str(uuid.uuid4()))
    email_id = Column(String(128), nullable=False, unique=True, index=True)
    first_name = Column(String(36), nullable=False)
    last_name = Column(String(36))
    phone_no = Column(String(15), nullable=False)
    password_hash = Column(String(240), nullable=False)
    organization = Column(String(128), nullable=False)
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    
    # One User (Bank Manager) -> Many Transactions
    transactions = relationship(
        "Transaction",
        back_populates="tenant",
        cascade="all, delete-orphan"
    )

    # One User (Bank Manager) -> Many Fraud Rings
    fraud_rings = relationship(
        "FraudRingSummary",
        back_populates="tenant",
        cascade="all, delete-orphan"
    )

    # One User -> May Uploaded JSON files
    json_files = relationship(
        "JSONStore",
        back_populates="tenant",
        cascade="all, delete-orphan"
    )

    # One User -> One FAISS Store (documents, index, metadata)
    faiss_store = relationship(
        "FaissIndexStore",
        back_populates="tenant",
        uselist=False,
        cascade="all, delete-orphan"
    )

    def set_password(self, password: str) -> None:
        self.password_hash = hash_password(password)

    def check_password(self, password: str) -> bool:
        return verify_password(hashed_password=self.password_hash, plain_password=password)


class Transaction(Base):
    """
    Raw Transactions Table (Partitioned logically by tenant_user_id)
    """
    __tablename__ = "transactions"

    # Primary key for the database row
    id = Column(Integer, primary_key=True, autoincrement=True)
    
    # Tenant relationship (Which bank manager uploaded this?)
    tenant_user_id = Column(String(36), ForeignKey("users.user_id", ondelete="CASCADE"), nullable=False, index=True)
    
    # Core Transaction Data
    transaction_id = Column(String(255), nullable=False, index=True)
    sender = Column(String(255), nullable=False, index=True)
    receiver = Column(String(255), nullable=False, index=True)
    amount = Column(Numeric(15, 2), nullable=False)
    timestamp = Column(DateTime, nullable=False)
    
    # Contextual Data (Money Mule Indicators)
    sender_country = Column(String(3))
    receiver_country = Column(String(3))
    sender_kyc = Column(String(50))
    txn_method = Column(String(50))
    device_id = Column(String(255))
    
    # Engineered Features
    sender_acct_age = Column(Integer)
    velocity_mins = Column(Float)
    is_round_amount = Column(Boolean)

    # ORM Relationship back to User
    tenant = relationship("User", back_populates="transactions")


class FraudRingSummary(Base):
    """
    Output Table storing the detected fraud rings from the MainEngine
    """
    __tablename__ = "fraud_rings_summary"

    id = Column(Integer, primary_key=True, autoincrement=True)

    # The RING_001 identifier generated by your engine
    ring_id = Column(String(50), nullable=False, index=True)
    
    # Tenant relationship
    tenant_user_id = Column(String(36), ForeignKey("users.user_id", ondelete="CASCADE"), nullable=False, index=True)
    
    # Ring Details
    pattern_type = Column(String(100), nullable=False)
    member_count = Column(Integer, nullable=False)
    risk_score = Column(Float, nullable=False)
    risk_category = Column(String(20), nullable=False)
    
    # Storing a list of accounts as a comma-separated string (or JSON if preferred)
    member_accounts = Column(Text, nullable=False)
    
    created_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    # ORM Relationship back to User
    tenant = relationship("User", back_populates="fraud_rings")


class JSONStore(Base):

    """
    Stores individual JSON files uploaded by the user.
    """

    __tablename__ = "json_store"

    id = Column(Integer, primary_key=True, autoincrement=True)
    
    tenant_user_id = Column(String(36), ForeignKey("users.user_id", ondelete="CASCADE"), nullable=False, index=True)

    filename = Column(String(255), index=True, nullable=False)
    json_data = Column(JSONB, nullable=False)

    uploaded_at = Column(DateTime, default=datetime.utcnow, nullable=False)

    tenant = relationship("User", back_populates="json_files")


class FaissIndexStore(Base):

    """
    Stores the FAISS vector database files (documents.json, index.faiss, metadata.pkl).
    Grouped by the user's UUID.
    """

    __tablename__ = "faiss_index_store"

    id = Column(Integer, primary_key=True, autoincrement=True)

    tenant_user_id = Column(String(36), ForeignKey("users.user_id", ondelete="CASCADE"), nullable=False, unique=True, index=True)

    documents = Column(JSONB, nullable=True)
    faiss_index = Column(LargeBinary, nullable=True)
    metadata_pkl = Column(LargeBinary, nullable=True)

    last_updated = Column(DateTime, default=datetime.utcnow, onupdate=datetime.utcnow, nullable=False)

    tenant = relationship("User", back_populates="faiss_store")
